name: job-step-conditions
on:
  push:
    branches: main 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: step1:"build started"
      run: echo "Build started"
    - name: step2:"stimulate failure"
      run: echo "stimulate failure"
    - name: step3:"only if privous step succedded"
      if: success()
      run: echo "previous step succedded run step3"
      
  test:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
    - name: run tests
      run: echo "running tests"
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
    - name: deploy if build success
      if: success()
      run: echo "deployed as build succedded"
    - name: deploy if build failed
      if: failure()
      run: echo "deployed as build failed"

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: success()
    steps:
    - name: run if deploy is successfull
      run: echo "Notifying team about successfull deployement"

